"""
Interview glossary — structured bilingual data.

Source: knowledge.md (the flat prose version). This module is the clean,
app-readable version: one dict per term. Scope = the 5 interview-core
categories (RAG, Embeddings, Agents, LangChain, LangGraph).

Each entry:
    id        - stable key
    category  - one of CATEGORIES
    term_en   - English term
    term_zh   - Chinese term
    def_en    - short English definition
    analogy_en- "Think of it like..." plain-English analogy
    def_zh    - Chinese definition
    analogy_zh- Chinese analogy
    demo      - optional lab id this concept maps to (links Learn -> See it work)
"""

from __future__ import annotations

CATEGORIES = [
    "Foundations",
    "RAG",
    "Embeddings & Vector Search",
    "Agents & Tool Use",
    "LangChain",
    "LangGraph",
]

# Lab ids used by the `demo` field (must match tabs in interview_prep.py).
DEMO_EMBEDDINGS = "embeddings"
DEMO_CHUNKING = "chunking"
DEMO_RAG = "rag"
DEMO_AGENT = "agent"
DEMO_TRANSFORMER = "transformer"

TERMS: list[dict] = [
    # ===================== Foundations =====================
    {
        "id": "llm",
        "category": "Foundations",
        "term_en": "LLM (large language model)",
        "term_zh": "大语言模型",
        "def_en": "A model trained on huge amounts of text that predicts the next token to generate language.",
        "analogy_en": "Like an extremely well-read autocomplete: it has read a huge library and, given some text, guesses the most fitting next piece — one token at a time — to write fluent answers.",
        "def_zh": "用海量文本训练、通过预测下一个词元来生成语言的模型。",
        "analogy_zh": "像一个博览群书的超级自动补全：它读过一座巨大的图书馆，看到一段文字就猜出最贴切的下一段——一次一个词元——从而写出流畅的回答。",
    },
    {
        "id": "token",
        "category": "Foundations",
        "term_en": "Token / tokenization",
        "term_zh": "词元 / 分词",
        "def_en": "The sub-word pieces a model reads and is billed by.",
        "analogy_en": "The AI can't read a whole word in one gulp, so it chops text into little pieces called tokens, like breaking a chocolate bar into squares. 'Unbelievable' becomes 'un' + 'believ' + 'able'. Just like a shop charges per square of chocolate, the AI charges per token.",
        "def_zh": "模型读取和计费的最小文字单位。",
        "analogy_zh": "AI 不能一口吞下整个单词，所以把文字切成小块，叫“词元”，就像把一整块巧克力掰成小方块再吃。“unbelievable”会被切成“un”+“believ”+“able”。就像商店按巧克力方块数收钱，AI 也按词元数收费。",
    },
    {
        "id": "context_window",
        "category": "Foundations",
        "term_en": "Context window",
        "term_zh": "上下文窗口",
        "def_en": "The most tokens the model can look at in one go.",
        "analogy_en": "Imagine a desk that only holds so many papers. Pile on too many and the bottom ones fall off the edge. The AI's 'desk' is its context window: once full, the oldest notes slide off and are forgotten.",
        "def_zh": "模型一次能看的最多词元数量。",
        "analogy_zh": "想象一张桌子只能放下有限的纸，放太多最下面的就会掉下去。AI 也有这样一张“桌子”，叫上下文窗口；一旦放满，最早的笔记就会滑落、被忘记。",
    },
    {
        "id": "inference",
        "category": "Foundations",
        "term_en": "Inference",
        "term_zh": "推理",
        "def_en": "Running a finished model to get an answer (not training it).",
        "analogy_en": "Training is like a student studying all year. Inference is test day, when the student actually answers using what they learned. Every time you ask the AI and it replies, that's inference, not studying.",
        "def_zh": "用训练好的模型生成答案（而不是训练它）。",
        "analogy_zh": "训练像学生用一整年学习；推理是考试当天，用学到的东西真正答题。你每次问 AI、它回答的那一刻，就是推理，而不是学习。",
    },
    {
        "id": "temperature",
        "category": "Foundations",
        "term_en": "Temperature / top-p",
        "term_zh": "温度 / top-p",
        "def_en": "Dials that control how random the output is.",
        "analogy_en": "Think of an ice-cream machine with a 'surprise' dial. Turn it to 0 and you get plain vanilla every time. Turn it up high and it picks wild random flavors. Low = safe and predictable; high = creative and surprising.",
        "def_zh": "控制输出随机程度的旋钮。",
        "analogy_zh": "想象一台带“惊喜”旋钮的冰淇淋机。转到 0，每次都给你原味香草；调高，它就挑各种古怪口味。温度低=稳妥可预测；温度高=有创意、爱给惊喜。",
    },
    {
        "id": "message_roles",
        "category": "Foundations",
        "term_en": "Message roles (system / user / assistant)",
        "term_zh": "消息角色",
        "def_en": "The system / user / assistant parts of a chat.",
        "analogy_en": "Like a school play where everyone has a part. The 'system' is the director who says 'you're a friendly teacher.' The 'user' is you asking. The 'assistant' is the AI saying its lines back.",
        "def_zh": "对话里的 system / user / assistant 三种身份。",
        "analogy_zh": "像一场校园话剧，每人有角色。“system”是导演，说“你是一位友善的老师”；“user”是你提问；“assistant”是 AI 说出它的台词。",
    },
    {
        "id": "hallucination",
        "category": "Foundations",
        "term_en": "Hallucination",
        "term_zh": "幻觉",
        "def_en": "A confident answer that is actually made up.",
        "analogy_en": "Picture a kid who doesn't know a test answer but confidently writes something that sounds right. The AI does this too: it can invent a 'fact,' like naming a book that was never written, and say it as if it's true.",
        "def_zh": "听起来很自信、其实是编造的答案。",
        "analogy_zh": "想象一个孩子不知道考题答案，却很自信地写下听上去对的东西。AI 也会这样：它可能“编”出一个事实，比如说出一本根本不存在的书，还当成真的说出来。",
    },
    {
        "id": "in_context_learning",
        "category": "Foundations",
        "term_en": "In-context learning (zero/few-shot)",
        "term_zh": "上下文学习 / 少样本学习",
        "def_en": "Teaching by examples in the prompt, no retraining.",
        "analogy_en": "Like showing a kid how to sort two socks yourself, then they copy you for the rest, no 'sock school' needed. You put a few examples right in your question and the AI copies the pattern.",
        "def_zh": "在提示里给例子来教它，不用重新训练。",
        "analogy_zh": "就像你先帮孩子配好两双袜子做示范，他就照着把剩下的配完，不用去上“袜子学校”。你在问题里放几个例子，AI 就照着模仿。",
    },
    {
        "id": "chain_of_thought",
        "category": "Foundations",
        "term_en": "Chain-of-thought (CoT)",
        "term_zh": "思维链",
        "def_en": "Asking the model to reason step by step.",
        "analogy_en": "When a math problem is tricky, the teacher says 'show your work.' Thinking out loud, one step at a time, means fewer mistakes. Telling the AI to 'think step by step' makes it work through the problem.",
        "def_zh": "让模型一步步推理。",
        "analogy_zh": "数学题难的时候，老师会说“把过程写出来”。一步步想，错得少。让 AI“一步步想”，它就会推导，而不是脱口而出答案。",
    },
    {
        "id": "structured_output",
        "category": "Foundations",
        "term_en": "Structured output",
        "term_zh": "结构化输出",
        "def_en": "Forcing a tidy JSON/form-shaped answer.",
        "analogy_en": "Instead of telling a long story about your toy, you fill in a neat form: Name: teddy, Color: brown, Size: big. Structured output makes the AI fill in a tidy form so a computer can read it easily.",
        "def_zh": "强制模型输出整齐的 JSON/表格式答案。",
        "analogy_zh": "与其讲一长段关于你玩具的故事，不如填一张整齐的表：名字：泰迪；颜色：棕色；大小：大。结构化输出就是让 AI 填整齐的表，方便电脑读取。",
    },
    {
        "id": "transformer",
        "category": "Foundations",
        "term_en": "Transformer",
        "term_zh": "Transformer 架构",
        "def_en": "The neural-network architecture behind modern LLMs; it processes all tokens at once and uses attention to mix information between them.",
        "analogy_en": "Imagine everyone at a meeting reading every other person's notes at the same time and deciding whose notes matter most. That 'everyone looks at everyone' trick is attention, and the Transformer is the meeting room built around it. Stack many such rooms and you get GPT/Claude.",
        "def_zh": "现代大模型背后的神经网络架构；它一次性处理所有词元，并用注意力机制在词元之间交换信息。",
        "analogy_zh": "想象开会时每个人同时读所有其他人的笔记，并判断谁的笔记最重要。这种“人人看人人”的技巧就是注意力，而 Transformer 就是围绕它建的会议室。把很多这样的房间叠起来，就成了 GPT / Claude。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "self_attention",
        "category": "Foundations",
        "term_en": "Self-attention",
        "term_zh": "自注意力",
        "def_en": "The step where each token looks at every other token in the same sequence and pulls in the most relevant information.",
        "analogy_en": "Reading 'it' in 'the cat sat because it was tired', your brain glances back to 'cat' to know what 'it' means. Self-attention is the model doing that glancing — every word checks every other word and borrows meaning from the ones that matter.",
        "def_zh": "每个词元都去看同一句话里所有其他词元，并吸收最相关信息的步骤。",
        "analogy_zh": "读“猫坐下因为它累了”里的“它”时，你的大脑会回看“猫”才知道“它”指谁。自注意力就是模型在做这种回看——每个词都看遍其他词，并从重要的词那里借来含义。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "qkv",
        "category": "Foundations",
        "term_en": "Query, Key, Value (Q/K/V)",
        "term_zh": "查询 / 键 / 值 (Q/K/V)",
        "def_en": "Three vectors each token produces. A token's Query is matched against every token's Key to get attention weights, which then blend the Values.",
        "analogy_en": "Like a search engine for meaning: your Query is what you're looking for, each item's Key is its label, and the match score decides how much of each item's Value (its content) you take. Attention = soft, weighted lookup over the whole sentence.",
        "def_zh": "每个词元生成的三个向量。用某词元的“查询”去和所有词元的“键”匹配得到注意力权重，再用权重加权汇总各词元的“值”。",
        "analogy_zh": "就像一个意义搜索引擎：你的“查询”是你想找的东西，每个条目的“键”是它的标签，匹配分决定你从每个条目的“值”（内容）里取多少。注意力 = 对整句话做柔性的加权检索。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "cross_attention",
        "category": "Foundations",
        "term_en": "Cross-attention",
        "term_zh": "交叉注意力",
        "def_en": "Attention where the Queries come from one sequence but the Keys/Values come from another (e.g. decoder attending to an encoder, or to retrieved documents).",
        "analogy_en": "Self-attention is re-reading your own essay; cross-attention is writing your essay while glancing at a separate source book. The Queries are 'what I'm writing now', the Keys/Values are 'the source I'm looking things up in'.",
        "def_zh": "查询来自一个序列、而键/值来自另一个序列的注意力（例如解码器关注编码器，或关注检索到的文档）。",
        "analogy_zh": "自注意力是反复读自己写的文章；交叉注意力是边写文章边参考另一本资料书。查询是“我现在在写的内容”，键/值是“我正在查阅的资料来源”。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "encoder_decoder",
        "category": "Foundations",
        "term_en": "Encoder vs Decoder",
        "term_zh": "编码器 vs 解码器",
        "def_en": "Two halves of a Transformer. An encoder reads the whole input bidirectionally to build meaning vectors (no generation); a decoder generates text one token at a time, looking only at past tokens (causal masking).",
        "analogy_en": "The encoder is a reader who studies the whole page at once and writes a summary of its meaning. The decoder is a writer who produces words one at a time and is only allowed to see what they've already written, never the future.",
        "def_zh": "Transformer 的两半。编码器双向地读完整个输入、建立含义向量（不生成文字）；解码器一次生成一个词元，且只能看已经生成的词元（因果遮挡）。",
        "analogy_zh": "编码器像一位读者，一次看完整页、写出它含义的总结；解码器像一位作者，一次写一个词，而且只能看自己已经写出的内容，看不到未来。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "model_families",
        "category": "Foundations",
        "term_en": "Encoder-only / Decoder-only / Encoder–decoder",
        "term_zh": "纯编码器 / 纯解码器 / 编码器-解码器",
        "def_en": "The three Transformer layouts: encoder-only (BERT, embedding models) for understanding; decoder-only (GPT, Claude) for generation; encoder–decoder (T5, translation) where the decoder cross-attends to the encoder.",
        "analogy_en": "Encoder-only = a librarian who files things by meaning (search/embeddings). Decoder-only = a storyteller who just keeps writing (chat LLMs). Encoder–decoder = a translator who first reads the whole source, then writes the translation while glancing back at it.",
        "def_zh": "三种 Transformer 结构：纯编码器（BERT、嵌入模型）用于理解；纯解码器（GPT、Claude）用于生成；编码器-解码器（T5、翻译）中解码器对编码器做交叉注意力。",
        "analogy_zh": "纯编码器=按含义归档的图书管理员（搜索/嵌入）；纯解码器=不停往下写的讲故事的人（聊天大模型）；编码器-解码器=先读完原文、再边回看边翻译的译者。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "softmax",
        "category": "Foundations",
        "term_en": "Softmax",
        "term_zh": "Softmax 归一化",
        "def_en": "A function that turns a list of raw scores (logits) into probabilities that sum to 1.",
        "analogy_en": "It's the vote-counter: take everyone's raw enthusiasm, exaggerate the leaders a bit, and turn it all into percentages that add up to 100%. Used both inside attention (to weight tokens) and at the output (to pick the next token).",
        "def_zh": "把一串原始分数（logits）变成加起来等于 1 的概率的函数。",
        "analogy_zh": "它像计票员：把每个选项的原始热度拿来，稍微放大领先者，再换算成加起来等于 100% 的百分比。它既用在注意力内部（给词元加权），也用在输出端（挑下一个词元）。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "logits_unembedding",
        "category": "Foundations",
        "term_en": "Logits & unembedding",
        "term_zh": "Logits 与反嵌入",
        "def_en": "The model's final hidden vector is multiplied by the vocabulary matrix to score every possible next token; those raw scores are 'logits', and softmax turns them into next-token probabilities.",
        "analogy_en": "After all the thinking, the model holds one summary vector. It compares that vector against every word's 'fingerprint' in its dictionary; the closest matches score highest. Softmax converts those scores to probabilities, and one word is chosen as the next token.",
        "def_zh": "模型最后的隐藏向量与词表矩阵相乘，为每个可能的下一个词元打分；这些原始分数就是“logits”，softmax 把它们变成下一个词元的概率。",
        "analogy_zh": "经过全部思考后，模型手里握着一个总结向量。它把这个向量与词典里每个词的“指纹”作比较，最接近的得分最高。softmax 把这些分数变成概率，然后选出一个词作为下一个词元。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "positional_encoding",
        "category": "Foundations",
        "term_en": "Positional encoding",
        "term_zh": "位置编码",
        "def_en": "Extra signals added to token embeddings so the model knows word order (attention by itself is order-blind).",
        "analogy_en": "Attention treats a sentence like a bag of words — it could read 'dog bites man' and 'man bites dog' the same way. Positional encoding stamps a seat number on each word so the model knows who came first.",
        "def_zh": "加到词元嵌入上的额外信号，让模型知道词序（注意力本身分不清顺序）。",
        "analogy_zh": "注意力把句子当成一袋词——“狗咬人”和“人咬狗”在它眼里可能一样。位置编码给每个词盖上一个座位号，模型才知道谁先谁后。",
        "demo": DEMO_TRANSFORMER,
    },
    {
        "id": "rag_vs_finetuning",
        "category": "Foundations",
        "term_en": "RAG vs fine-tuning vs long-context",
        "term_zh": "RAG / 微调 / 长上下文",
        "def_en": "Three ways to give the AI new knowledge.",
        "analogy_en": "RAG is an open-book test: the AI peeks at the right library book while answering. Fine-tuning is sending it to school to truly learn a skill. Long-context is handing it the one page it needs right before you ask.",
        "def_zh": "给 AI 补充新知识的三种方法。",
        "analogy_zh": "RAG 是开卷考试：答题时偷看正确的那本书。微调是送它去上学、真正学会一项新技能。长上下文是直接把它需要的那一页递给它再提问。",
        "demo": DEMO_RAG,
    },
    # ===================== RAG =====================
    {
        "id": "rag",
        "category": "RAG",
        "term_en": "RAG (Retrieval-Augmented Generation)",
        "term_zh": "检索增强生成",
        "def_en": "Retrieve relevant text first, then let the model answer grounded in it.",
        "analogy_en": "An open-book test: before answering, the AI looks up the most relevant pages and answers from them instead of guessing from memory.",
        "def_zh": "先检索相关文字，再让模型据此作答。",
        "analogy_zh": "开卷考试：回答前，AI 先查到最相关的几页，照着这些页作答，而不是凭记忆瞎猜。",
        "demo": DEMO_RAG,
    },
    {
        "id": "indexing_vs_query",
        "category": "RAG",
        "term_en": "Indexing vs query phase",
        "term_zh": "建索引阶段 / 查询阶段",
        "def_en": "Build the searchable store once; then answer fast each time.",
        "analogy_en": "A librarian spends the weekend shelving every book with labels (indexing). Then when you ask, she instantly grabs the right book (querying). The hard sorting happens once; answering is then quick.",
        "def_zh": "先一次性建好可搜索的库，之后每次都能快速回答。",
        "analogy_zh": "图书管理员花一个周末把每本书摆到正确书架并贴标签（建索引）。之后你一提问，她立刻走到对应书架拿书（查询）。难的整理只做一次，回答就很快。",
        "demo": DEMO_RAG,
    },
    {
        "id": "chunking",
        "category": "RAG",
        "term_en": "Chunking (size / overlap)",
        "term_zh": "分块 / 块大小 / 重叠",
        "def_en": "Cutting documents into bite-size pieces to embed.",
        "analogy_en": "A whole pizza is too big for one bite, so you cut it into slices. The AI slices documents into 'chunks.' Overlap means each slice shares a little crust with the next, so nothing important is lost at the cut.",
        "def_zh": "把文档切成便于嵌入的小块。",
        "analogy_zh": "一整张披萨一口吃不下，所以切成片。AI 把大文档切成“块”。重叠是指每片和下一片共享一点饼边，免得切口处的重要内容丢失。",
        "demo": DEMO_CHUNKING,
    },
    {
        "id": "chunking_strategies",
        "category": "RAG",
        "term_en": "Chunking strategies",
        "term_zh": "分块策略",
        "def_en": "Different ways to split (fixed, recursive, semantic, parent-document...).",
        "analogy_en": "Different ways to cut the pizza: equal squares, along the natural lines, or take a tiny bite but keep the whole slice nearby. Each cutting style trades off how well you find and understand the pieces.",
        "def_zh": "不同的切分方式（固定、递归、语义、父文档……）。",
        "analogy_zh": "切披萨的不同方法：切成相等方块、沿天然纹路切、或者咬一小口但把整片留在旁边以备需要。每种切法在“好不好找、好不好懂”上各有取舍。",
        "demo": DEMO_CHUNKING,
    },
    {
        "id": "contextual_retrieval",
        "category": "RAG",
        "term_en": "Contextual retrieval",
        "term_zh": "上下文检索",
        "def_en": "Add a context label to each chunk before embedding.",
        "analogy_en": "A sticky note that just says '30 days' is useless alone. So you add a label: 'Return policy: 30 days.' Now anyone who finds it understands. The AI tags each chunk so it makes sense even when found alone.",
        "def_zh": "嵌入前给每个块加上下文标签。",
        "analogy_zh": "一张只写着“30 天”的便利贴单独看毫无意义。于是你加个标签：“退货政策：30 天”。这样谁找到都懂。AI 给每个块贴上小标签，即使单独被找到也讲得通。",
    },
    {
        "id": "top_k",
        "category": "RAG",
        "term_en": "Top-k",
        "term_zh": "取前 k 个",
        "def_en": "How many chunks the retriever brings back.",
        "analogy_en": "When you ask the librarian, do you want the 1 best book or the top 3? 'Top-k' is that number. k=3 means 'bring me the 3 closest matches to my question.'",
        "def_zh": "检索器一次返回多少个块。",
        "analogy_zh": "你找管理员帮忙，是要 1 本最好的书，还是前 3 本最好的？“Top-k”就是这个数字。k=3 意思是“给我和问题最接近的 3 个”。",
        "demo": DEMO_RAG,
    },
    {
        "id": "mmr",
        "category": "RAG",
        "term_en": "MMR (maximal marginal relevance)",
        "term_zh": "最大边际相关性",
        "def_en": "Pick relevant but varied chunks, not duplicates.",
        "analogy_en": "If you ask for dog books, you don't want 3 copies of the same one; you want 3 different helpful ones. MMR makes the AI grab varied chunks instead of near-identical twins.",
        "def_zh": "既相关又多样，避免重复。",
        "analogy_zh": "你要狗的书，不想拿到 3 本一模一样的，而想要 3 本不同的好书。MMR 让 AI 取到多样的块，而不是几乎一样的“双胞胎”。",
    },
    {
        "id": "hybrid_search",
        "category": "RAG",
        "term_en": "Hybrid search",
        "term_zh": "混合检索",
        "def_en": "Mix meaning-based and exact-keyword search.",
        "analogy_en": "Two ways to find a book: by what it's about, or by its exact title words. Hybrid uses both, so you don't miss a book that uses a special exact name like a serial number 'X-200.'",
        "def_zh": "结合“按意思”和“按关键词”两种搜索。",
        "analogy_zh": "找书有两种方式：按内容意思，或按确切的书名词。混合检索两者都用，这样就不会漏掉用了特殊确切名字（比如序列号“X-200”）的书。",
    },
    {
        "id": "reranking",
        "category": "RAG",
        "term_en": "Reranking",
        "term_zh": "重排序",
        "def_en": "A careful second pass that keeps only the best chunks.",
        "analogy_en": "First you grab a big armful of maybe-useful books (say 50). Then a picky helper looks closely and keeps only the 5 best. Reranking is that careful second sort that tosses the so-so ones.",
        "def_zh": "再仔细排一遍，只留最好的块。",
        "analogy_zh": "先抱回一大堆可能有用的书（比如 50 本），再让一个挑剔的助手仔细看，只留最好的 5 本给你。重排序就是那次仔细的二次筛选，扔掉一般般的。",
    },
    {
        "id": "query_rewriting",
        "category": "RAG",
        "term_en": "Query rewriting / multi-query / HyDE",
        "term_zh": "查询改写 / 多查询 / HyDE",
        "def_en": "Reshape a vague question for better searching.",
        "analogy_en": "A kid asks 'what about the blue one?' and you have no idea what they mean. So you turn it into a full question: 'How much does the blue bike cost?' The AI rewrites fuzzy questions into clear ones before searching.",
        "def_zh": "把含糊的问题改写得更好搜。",
        "analogy_zh": "小孩问“那蓝色的那个呢？”你根本不知道指什么。于是你把它变成完整问题：“那辆蓝色自行车多少钱？”AI 在搜索前先把模糊问题改写成清楚完整的。",
        "demo": DEMO_RAG,
    },
    {
        "id": "grounding",
        "category": "RAG",
        "term_en": "Grounding / faithfulness",
        "term_zh": "有据可依 / 忠实度",
        "def_en": "The answer must come from the retrieved text.",
        "analogy_en": "Like a kid only allowed to answer using the book in front of them, no made-up extras. 'Grounded' means the answer comes straight from the real pages. If it's not in the book, the honest answer is 'I don't know.'",
        "def_zh": "答案必须来自检索到的文字。",
        "analogy_zh": "像一个只能用眼前这本书回答、不能瞎编的孩子。“有据”就是答案直接来自真实的书页。如果书里没有，诚实的回答就是“我不知道”。",
        "demo": DEMO_RAG,
    },
    {
        "id": "corrective_rag",
        "category": "RAG",
        "term_en": "Corrective / Self / Agentic RAG",
        "term_zh": "纠正式 / 自我 / 智能体 RAG",
        "def_en": "Grade what you found and retry if it's bad.",
        "analogy_en": "You look for your toy, check a box, it's not there, so you stop, think 'where else?', and check a better box. The AI does this: if the pages found don't help, it changes its search and tries again instead of guessing.",
        "def_zh": "给检索结果打分，不好就重试。",
        "analogy_zh": "你找玩具，翻开一个箱子没有，于是停下想“还能在哪？”，再翻一个更可能的箱子。AI 也这样：找到的页帮不上忙，就改搜索再试，而不是瞎猜。",
        "demo": DEMO_RAG,
    },
    # ============ Embeddings & Vector Search ============
    {
        "id": "embedding",
        "category": "Embeddings & Vector Search",
        "term_en": "Embedding (vector)",
        "term_zh": "嵌入 / 向量",
        "def_en": "A list of numbers that captures a text's meaning.",
        "analogy_en": "Imagine every word gets a house on a giant map, and similar-meaning words live close together. 'Dog' and 'puppy' are next-door neighbors; 'dog' and 'tax' live in different cities. An embedding is a word's address on that meaning-map, in numbers.",
        "def_zh": "一串能表示文字含义的数字。",
        "analogy_zh": "想象每个词在一张大地图上都有一栋房子，意思相近的词住得近。“狗”和“小狗”是邻居；“狗”和“税”住在不同城市。嵌入就是一个词在这张“含义地图”上的地址，用数字写出来。",
        "demo": DEMO_EMBEDDINGS,
    },
    {
        "id": "embedding_model",
        "category": "Embeddings & Vector Search",
        "term_en": "Embedding model",
        "term_zh": "嵌入模型",
        "def_en": "The tool that turns text into those vectors.",
        "analogy_en": "It's the mapmaker — the helper that decides where each word or sentence goes on the meaning-map. It's a different helper from the one that writes the answers.",
        "def_zh": "把文字变成向量的工具。",
        "analogy_zh": "它是“绘图员”，决定每个词或句子在含义地图上放哪。它和负责写答案的那个助手是不同的工具。",
        "demo": DEMO_EMBEDDINGS,
    },
    {
        "id": "vector_store",
        "category": "Embeddings & Vector Search",
        "term_en": "Vector store / database",
        "term_zh": "向量库 / 向量数据库",
        "def_en": "Where embeddings are saved and searched.",
        "analogy_en": "A giant address book that remembers where everything lives on the meaning-map, so you can quickly look up the nearest neighbors. Chroma, Pinecone, pgvector are like different brands of it.",
        "def_zh": "保存并搜索嵌入向量的地方。",
        "analogy_zh": "一本巨大的通讯录，记住含义地图上每样东西住在哪，方便你快速查到最近的邻居。Chroma、Pinecone、pgvector 就像这本通讯录的不同品牌。",
        "demo": DEMO_EMBEDDINGS,
    },
    {
        "id": "cosine_similarity",
        "category": "Embeddings & Vector Search",
        "term_en": "Cosine similarity",
        "term_zh": "余弦相似度",
        "def_en": "A score for how close two vectors are.",
        "analogy_en": "A way to measure how close two houses are on the meaning-map. A high score like 0.95 means 'right next door, almost the same'; a low score means 'far away, totally different.'",
        "def_zh": "衡量两个向量有多接近的分数。",
        "analogy_zh": "一种衡量含义地图上两栋房子有多近的方法。0.95 这样的高分表示“就在隔壁，几乎一样”；低分表示“离得很远，完全不同”。",
        "demo": DEMO_EMBEDDINGS,
    },
    {
        "id": "ann_hnsw",
        "category": "Embeddings & Vector Search",
        "term_en": "ANN / HNSW",
        "term_zh": "近似最近邻 / HNSW",
        "def_en": "Fast approximate nearest-neighbor search.",
        "analogy_en": "With a million houses, checking every one to find the closest takes forever. ANN is a clever shortcut that finds very-close neighbors super fast, like using highways instead of walking every street.",
        "def_zh": "快速的近似最近邻搜索。",
        "analogy_zh": "要是有一百万栋房子，挨个检查找最近的会花很久。ANN 是个聪明的捷径，能极快找到很近的邻居，就像走高速而不是把每条街都走一遍。",
    },
    {
        "id": "dimensionality",
        "category": "Embeddings & Vector Search",
        "term_en": "Dimensionality",
        "term_zh": "维度",
        "def_en": "How many numbers are in each vector.",
        "analogy_en": "A simple map uses 2 directions (left-right, up-down). The meaning-map uses hundreds at once to capture detail. More directions means it can tell apart more tiny differences in meaning.",
        "def_zh": "每个向量里有多少个数字。",
        "analogy_zh": "简单地图只用 2 个方向（左右、上下）。含义地图同时用上百个方向来表达更多细节。维度越多，越能分辨出意思上的细微差别。",
        "demo": DEMO_EMBEDDINGS,
    },
    # ===================== Agents & Tool Use =====================
    {
        "id": "agent",
        "category": "Agents & Tool Use",
        "term_en": "Agent",
        "term_zh": "智能体",
        "def_en": "An LLM that can take actions in a loop, not just chat.",
        "analogy_en": "A plain AI only talks. An agent can also do things, like a helper who fetches a tool, uses it, and comes back. Ask 'what's the weather?' and instead of guessing, it goes and checks a weather tool first.",
        "def_zh": "能在循环里采取行动、不只聊天的 LLM。",
        "analogy_zh": "普通 AI 只会说话；智能体还能做事，像一个会起身去拿工具、用完再回来的助手。你问“天气怎么样？”，它不瞎猜，而是先去查天气工具。",
        "demo": DEMO_AGENT,
    },
    {
        "id": "tool_calling",
        "category": "Agents & Tool Use",
        "term_en": "Tool calling / function calling",
        "term_zh": "工具调用 / 函数调用",
        "def_en": "The model asks to run a function; you run it and return the result.",
        "analogy_en": "Like a kid who can't reach the cookie jar asking a grown-up 'please get the cookies.' The AI can't check the weather itself, so it asks for get_weather('Paris'); you run it and hand back '18 degrees.'",
        "def_zh": "模型请求运行某个函数，你运行后把结果交回。",
        "analogy_zh": "像够不到饼干罐的小孩对大人说“请帮我拿饼干”。AI 自己查不了天气，就请求工具 get_weather('Paris')；你运行后递回“18 度”，AI 接着往下做。",
        "demo": DEMO_AGENT,
    },
    {
        "id": "tool_schema",
        "category": "Agents & Tool Use",
        "term_en": "Tool schema",
        "term_zh": "工具描述 / 模式",
        "def_en": "The description of a tool's name, inputs, and purpose.",
        "analogy_en": "The instruction label on a tool. A juice machine labeled 'put in fruit, get out juice.' The schema tells the AI: this tool is get_weather and it needs a city name.",
        "def_zh": "描述工具名字、输入和用途的说明。",
        "analogy_zh": "工具上的说明标签。一台果汁机标着“放水果，出果汁”。schema 告诉 AI：这个工具叫 get_weather，需要一个城市名。",
        "demo": DEMO_AGENT,
    },
    {
        "id": "react",
        "category": "Agents & Tool Use",
        "term_en": "ReAct",
        "term_zh": "边想边做",
        "def_en": "A reason-then-act loop.",
        "analogy_en": "Think out loud, then act, then repeat. 'I need the price (think) -> look it up (act) -> it's $20 (result) -> now I can answer.' Like solving a treasure hunt one clue at a time.",
        "def_zh": "“推理—行动”的循环。",
        "analogy_zh": "先想出声，再行动，再重复。“我需要价格（想）→ 我去查（做）→ 是 20 元（看结果）→ 现在能回答了。”像一步步解寻宝线索。",
        "demo": DEMO_AGENT,
    },
    {
        "id": "agent_executor",
        "category": "Agents & Tool Use",
        "term_en": "AgentExecutor (deprecated)",
        "term_zh": "AgentExecutor（已弃用）",
        "def_en": "LangChain's old agent runtime, replaced by create_agent.",
        "analogy_en": "This was the OLD toy for building agents. There's a newer, better toy now (create_agent). In an interview, show you know the new one is what people actually use today.",
        "def_zh": "LangChain 旧的智能体运行器，已被 create_agent 取代。",
        "analogy_zh": "这是搭智能体用的“旧玩具”。现在有更好的新玩具（create_agent）。面试时最好表现出你知道大家如今用的是新的那个。",
    },
    {
        "id": "multi_agent",
        "category": "Agents & Tool Use",
        "term_en": "Multi-agent / supervisor / handoff",
        "term_zh": "多智能体 / 主管 / 交接",
        "def_en": "Several specialized agents working together.",
        "analogy_en": "A team of specialists. One 'boss' helper hears your question and passes it to the right expert: math questions to the math helper, art to the art helper. They work as a team.",
        "def_zh": "多个各有专长的智能体协作。",
        "analogy_zh": "一队专家。一个“主管”助手听你的问题，再交给合适的专家：数学问题给数学助手，美术问题给美术助手。他们像团队一样配合。",
    },
    {
        "id": "sub_agent",
        "category": "Agents & Tool Use",
        "term_en": "Sub-agent",
        "term_zh": "子智能体",
        "def_en": "An agent another agent calls for a smaller task.",
        "analogy_en": "When one helper has a big job, it hires a little helper for one piece, like a chef asking a kitchen helper to just chop the onions.",
        "def_zh": "被另一个智能体调用去做小任务的智能体。",
        "analogy_zh": "一个助手活儿太大时，就雇个小助手干其中一块，像大厨让厨房小工只切洋葱，自己做别的。",
    },
    {
        "id": "hitl",
        "category": "Agents & Tool Use",
        "term_en": "Human-in-the-loop (HITL)",
        "term_zh": "人在回路",
        "def_en": "Pause for a person's approval mid-task.",
        "analogy_en": "Like a kid who must ask a parent before spending allowance. The AI does most of the work but pauses to ask 'is this okay?' before something big, like sending money.",
        "def_zh": "中途暂停、等人确认。",
        "analogy_zh": "像花零花钱前要先问家长的小孩。AI 大部分活自己干，但做大事前（比如转账）会停下来问人一句“这样行吗？”。",
    },
    {
        "id": "memory",
        "category": "Agents & Tool Use",
        "term_en": "Memory (short / long-term)",
        "term_zh": "记忆（短期 / 长期）",
        "def_en": "Remembering within a chat vs across chats.",
        "analogy_en": "Short-term memory is remembering what we said earlier today in this same chat. Long-term memory is remembering your name next week, like a friend who remembers you.",
        "def_zh": "同一次对话内记住 vs 跨对话记住。",
        "analogy_zh": "短期记忆是记得我们今天这次聊过什么。长期记忆是你下周再来，它还记得你的名字和最喜欢的颜色，像个记得你的朋友。",
        "demo": DEMO_RAG,
    },
    {
        "id": "mcp",
        "category": "Agents & Tool Use",
        "term_en": "MCP (Model Context Protocol)",
        "term_zh": "模型上下文协议",
        "def_en": "An open standard plug for connecting models to tools/data.",
        "analogy_en": "A universal plug, like a USB port. Instead of every tool needing its own connector, MCP is one standard plug so the AI can connect to email, calendars, and apps easily.",
        "def_zh": "连接模型与外部工具/数据的开放标准。",
        "analogy_zh": "一个通用插口，像 USB。不用每个工具都配专属接头，MCP 是统一插口，让 AI 轻松连上邮箱、日历和各种应用。",
    },
    {
        "id": "guardrails",
        "category": "Agents & Tool Use",
        "term_en": "Guardrails",
        "term_zh": "护栏",
        "def_en": "Rules that keep the agent's behavior safe.",
        "analogy_en": "Like the bumpers in bowling that keep the ball out of the gutter. Guardrails stop the AI from doing something it shouldn't, like saying mean words or deleting important files.",
        "def_zh": "约束智能体行为的规则。",
        "analogy_zh": "像保龄球道边上的挡板，别让球掉进沟里。护栏就是阻止 AI 做不该做的事的规则，比如说脏话或删掉重要文件。",
    },
    # ===================== LangChain =====================
    {
        "id": "lcel",
        "category": "LangChain",
        "term_en": "LCEL (the '|' pipe)",
        "term_zh": "LCEL（| 管道）",
        "def_en": "Composing components with the pipe operator.",
        "analogy_en": "A factory conveyor belt where each station does one job and passes it on. The '|' connects the stations: shape the question -> ask the model -> tidy the answer.",
        "def_zh": "用管道符把组件拼起来。",
        "analogy_zh": "一条工厂传送带，每个工位干一件事再传给下一个。“|”把工位连起来：整理问题 → 问模型 → 整理答案。",
    },
    {
        "id": "runnable",
        "category": "LangChain",
        "term_en": "Runnable",
        "term_zh": "可运行对象",
        "def_en": "The shared .invoke / .stream / .batch interface.",
        "analogy_en": "A common 'start button' that works the same on every machine. No matter which factory part it is, you start it the same way, so they all snap together neatly.",
        "def_zh": "通用的 .invoke / .stream / .batch 接口。",
        "analogy_zh": "一个在每台机器上都一样的“启动按钮”。不管是哪个工厂部件，启动方式都一样，于是它们能整齐地拼到一起。",
    },
    {
        "id": "chain",
        "category": "LangChain",
        "term_en": "Chain",
        "term_zh": "链",
        "def_en": "A straight line of steps, one after another.",
        "analogy_en": "Like following a recipe top to bottom: mix -> bake -> frost. Each step leads to the next, and you don't go backwards.",
        "def_zh": "一条直线式、一步接一步的流程。",
        "analogy_zh": "像从上到下照菜谱做：搅拌 → 烘烤 → 抹糖霜。每步带到下一步，不能往回走。",
        "demo": DEMO_RAG,
    },
    {
        "id": "chatprompttemplate",
        "category": "LangChain",
        "term_en": "ChatPromptTemplate / MessagesPlaceholder",
        "term_zh": "聊天提示模板 / 消息占位符",
        "def_en": "A reusable prompt with a slot for history.",
        "analogy_en": "A fill-in-the-blanks form for talking to the AI. The placeholder is the blank where you slot in the conversation so far, so the AI remembers what was said.",
        "def_zh": "可复用的提示，带一个放历史的空位。",
        "analogy_zh": "一张和 AI 说话用的填空表。占位符就是那个空格，把“目前为止的对话”塞进去，AI 就记得之前说过什么。",
    },
    {
        "id": "output_parser",
        "category": "LangChain",
        "term_en": "Output parser",
        "term_zh": "输出解析器",
        "def_en": "Turns the model's text into structured data.",
        "analogy_en": "A translator that turns the AI's words into something tidy a computer can use, like turning 'yes!' into a checkmark (True).",
        "def_zh": "把模型的文字变成结构化数据。",
        "analogy_zh": "一个翻译员，把 AI 的话变成电脑好用的整齐形式，比如把“yes!”变成一个对勾（True）。",
    },
    {
        "id": "loader_splitter_retriever",
        "category": "LangChain",
        "term_en": "Document loader / splitter / retriever",
        "term_zh": "文档加载器 / 分割器 / 检索器",
        "def_en": "The RAG ingest-and-fetch parts.",
        "analogy_en": "The RAG kitchen crew: one loads the food (documents), one chops it into pieces (splitter), one fetches the right pieces when you're hungry (retriever).",
        "def_zh": "RAG 里负责装入和取出的部件。",
        "analogy_zh": "RAG 的厨房小队：一个把食材（文档）端进来，一个切成块（分割器），一个在你饿时取出正确的块（检索器）。",
        "demo": DEMO_CHUNKING,
    },
    {
        "id": "create_agent",
        "category": "LangChain",
        "term_en": "create_agent",
        "term_zh": "create_agent",
        "def_en": "The current high-level way to build a tool-using agent.",
        "analogy_en": "A ready-made kit for building a helper that can use tools. Instead of building from scratch, hand it a model and a box of tools and it's good to go.",
        "def_zh": "当前搭建工具型智能体的高层方式。",
        "analogy_zh": "一个现成的套件，用来搭能用工具的助手。不用从零做，把模型和一盒工具递给它，就能开工。",
        "demo": DEMO_AGENT,
    },
    # ===================== LangGraph =====================
    {
        "id": "stategraph",
        "category": "LangGraph",
        "term_en": "StateGraph",
        "term_zh": "状态图",
        "def_en": "The graph of nodes and edges you build.",
        "analogy_en": "A board-game map of 'what happens next.' Each space is a step, and arrows show which space you move to. You build this map to tell the AI how to flow through a task.",
        "def_zh": "你用节点和边搭起来的图。",
        "analogy_zh": "一张“接下来发生什么”的棋盘地图。每个格子是一步，箭头指向你接下来去哪格。你画这张图来告诉 AI 怎么走完一个任务。",
        "demo": DEMO_RAG,
    },
    {
        "id": "state",
        "category": "LangGraph",
        "term_en": "State",
        "term_zh": "状态",
        "def_en": "The shared data every node reads and updates.",
        "analogy_en": "A shared backpack everyone on the trip can reach into and add to. It holds everything the task needs so far: the question, the notes found, the answer.",
        "def_zh": "每个节点都能读写的共享数据。",
        "analogy_zh": "一个旅途中大家都能伸手取放东西的共享背包。它装着任务目前需要的一切：问题、找到的笔记、答案。",
        "demo": DEMO_RAG,
    },
    {
        "id": "reducer",
        "category": "LangGraph",
        "term_en": "Reducer (add_messages)",
        "term_zh": "Reducer（add_messages）",
        "def_en": "The rule for how updates merge into state.",
        "analogy_en": "A rule about how to put things in the backpack. 'add_messages' means new notes get stacked on top instead of replacing the old ones, so the whole conversation builds up.",
        "def_zh": "规定状态更新如何合并的规则。",
        "analogy_zh": "关于怎么往背包里放东西的规则。“add_messages”表示新笔记是叠在上面，而不是把旧的扔掉替换，这样整段对话会越积越多。",
        "demo": DEMO_RAG,
    },
    {
        "id": "node",
        "category": "LangGraph",
        "term_en": "Node",
        "term_zh": "节点",
        "def_en": "A function: state in, partial update out.",
        "analogy_en": "One stop on the map that does one job, like a kitchen station: it takes the backpack, does its task (e.g. 'find the pages'), and puts the result back.",
        "def_zh": "一个函数：传入状态，返回部分更新。",
        "analogy_zh": "地图上干一件事的一个站点，像厨房工位：拿过背包，做它的活（比如“找到那些页”），再把结果放回去。",
        "demo": DEMO_RAG,
    },
    {
        "id": "edge",
        "category": "LangGraph",
        "term_en": "Edge / conditional edge",
        "term_zh": "边 / 条件边",
        "def_en": "A fixed step vs a step chosen by a check.",
        "analogy_en": "Arrows on the board game. A normal arrow always points to the next space. A conditional arrow is a fork: you go left or right depending on what just happened.",
        "def_zh": "固定的下一步 vs 由判断决定的下一步。",
        "analogy_zh": "棋盘上的箭头。普通箭头总是指向下一格。条件箭头是岔路口：根据刚刚发生的事，决定往左还是往右。",
        "demo": DEMO_RAG,
    },
    {
        "id": "cycle",
        "category": "LangGraph",
        "term_en": "Cycle",
        "term_zh": "环 / 循环",
        "def_en": "A loop back to an earlier node.",
        "analogy_en": "A loop on the board that sends you back to try again, like 'go back 3 spaces and re-roll.' This is the special trick: a plain recipe can't loop, but this map can.",
        "def_zh": "回到前面某个节点的循环。",
        "analogy_zh": "棋盘上把你送回去再来一次的圈，像“后退 3 格、重掷骰子”。这是它的独门绝技：普通菜谱不能循环，这张图可以。",
        "demo": DEMO_RAG,
    },
    {
        "id": "checkpointer",
        "category": "LangGraph",
        "term_en": "Checkpointer",
        "term_zh": "检查点 / 存档器",
        "def_en": "The persistence layer for state.",
        "analogy_en": "A save point in a video game. It remembers where you are so you can pick up later. In-memory saves only while the game is on; SQLite saves to a file so it survives a restart.",
        "def_zh": "状态的持久化层。",
        "analogy_zh": "电子游戏里的存档点，记住你走到哪，方便以后接着玩。内存存档只在游戏开着时有效；SQLite 存到文件里，关机后也还在。",
        "demo": DEMO_RAG,
    },
    {
        "id": "thread_id",
        "category": "LangGraph",
        "term_en": "Thread / thread_id",
        "term_zh": "线程 / thread_id",
        "def_en": "A label identifying one conversation.",
        "analogy_en": "A name tag on each conversation so they don't get mixed up, like labeling each kid's lunchbox. 'user-123' keeps that person's chat separate.",
        "def_zh": "标识一次对话的标签。",
        "analogy_zh": "给每次对话贴的名牌，免得混在一起，像给每个孩子的午餐盒贴名字。“user-123”把那个人的聊天和别人分开。",
        "demo": DEMO_RAG,
    },
    {
        "id": "interrupt",
        "category": "LangGraph",
        "term_en": "Interrupt",
        "term_zh": "中断",
        "def_en": "Pause the graph for human input.",
        "analogy_en": "A pause button that stops the game to ask a person something before continuing, like a 'wait, check with a grown-up first' moment.",
        "def_zh": "暂停图、等待人输入。",
        "analogy_zh": "一个暂停按钮，停下来先问人一句再继续，像“等等，先问问大人”的那一刻。",
    },
    {
        "id": "subgraph",
        "category": "LangGraph",
        "term_en": "Subgraph",
        "term_zh": "子图",
        "def_en": "A graph used as a node inside another graph.",
        "analogy_en": "A mini board-game tucked inside the big one. One space on the big map opens into its own little set of steps, then returns to the main board.",
        "def_zh": "当作一个节点用在另一张图里的图。",
        "analogy_zh": "大棋盘里塞着的一张小棋盘。大地图上的一个格子悄悄展开成它自己的一套小步骤，走完再回到主盘。",
    },
    {
        "id": "streaming_modes",
        "category": "LangGraph",
        "term_en": "Streaming modes",
        "term_zh": "流式模式",
        "def_en": "Ways to stream progress (values / updates / messages).",
        "analogy_en": "Watching the answer appear letter by letter as it's typed, instead of waiting for the whole thing, like seeing a text message being written in real time.",
        "def_zh": "流式输出进度的方式（values/updates/messages）。",
        "analogy_zh": "看着答案一个字一个字蹦出来，而不是等整段都好，像看一条短信被实时打出来。",
        "demo": DEMO_RAG,
    },
]


def by_category() -> dict[str, list[dict]]:
    """Group terms by category, preserving CATEGORIES order."""
    grouped: dict[str, list[dict]] = {c: [] for c in CATEGORIES}
    for term in TERMS:
        grouped.setdefault(term["category"], []).append(term)
    return grouped


def get_term(term_id: str) -> dict | None:
    for term in TERMS:
        if term["id"] == term_id:
            return term
    return None
